services:
  db:
    container_name: redis
    image: redis
    networks:
      - hive-mind_network

  map-component:
    container_name: map_component
    build: 
      context: ./app
      dockerfile: Dockerfile.map_component
    ports:
      - 3000:3000
    networks:
      - hive-mind_network

  communication-control:
    container_name: communication_control
    build: 
      context: ./app
      dockerfile: Dockerfile.communication_control
    ports:
      - 8080:8080
    networks:
      - hive-mind_network

  hive-mind:
    container_name: hive_mind
    build: 
      context: ./app
      dockerfile: Dockerfile.hive_mind
    networks:
      - hive-mind_network
    depends_on:
      - communication-control

networks:
  hive-mind_network: