services:
  db:
    container_name: redis
    image: redis
    networks:
      - hive-mind_network

  map-component:
    container_name: map_component
    image: ant115ondzi/map-client
    ports:
      - 3000:3000
    networks:
      - hive-mind_network

  communication-control:
    container_name: communication_control
    image: ant115ondzi/communication-control
    ports:
      - 8080:8080
    networks:
      - hive-mind_network

  hive-mind:
    container_name: hive_mind
    image: ant115ondzi/hive-mind
    networks:
      - hive-mind_network
    depends_on:
      communication-control:
        condition: service_started

networks:
  hive-mind_network: