---
# tasks file for create_services
- name: Copy service files to the server
  copy:
    src: "{{item}}"
    dest: "{{SERVICE_PATH}}{{item}}"
  loop:
   - map_client.service
   - communication_control.service
   - hive_mind.service