FROM mcr.microsoft.com/dotnet/sdk:8.0

COPY ./hiveemulator/src/CommunicationControl/DevOpsProject.HiveMind.API/bin/Debug /app

WORKDIR /app/net8.0/

ENTRYPOINT [ "dotnet", "DevOpsProject.HiveMind.API.dll" ]