FROM node:latest

COPY ./hiveemulator/src/MapClient/package.json hiveemulator/src/MapClient/package.json

WORKDIR /hiveemulator/src/MapClient

RUN npm install

COPY ./hiveemulator/src/MapClient .

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "dev" ]