FROM mcr.microsoft.com/dotnet/sdk:8.0

COPY ./hiveemulator/src/CommunicationControl/DevOpsProject/bin/Debug /app

WORKDIR /app/net8.0/

EXPOSE 8080

ENTRYPOINT [ "dotnet", "DevOpsProject.CommunicationControl.API.dll" ]