FROM mcr.microsoft.com/dotnet/sdk:8.0

COPY . .

WORKDIR /hiveemulator/src/CommunicationControl/DevOpsProject.HiveMind.API

EXPOSE 5149

ENTRYPOINT [ "dotnet", "run", "DevOpsProject.HiveMind.API.csproj" ]