FROM node:latest

COPY ./hiveemulator/src/MapClient/package.json hiveemulator/src/MapClient/package.json

RUN cd /hiveemulator/src/MapClient && npm install

COPY ./hiveemulator/src/MapClient .

WORKDIR /hiveemulator/src/MapClient

ENTRYPOINT [ "npm", "run", "dev" ]