---
# tasks file for install_node
- name: Download nvm
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
    dest: '{{NVM_SCRIPT_DIR}}'
    mode: '0777'
- name: Install nvm
  command: '{{NVM_SCRIPT_DIR}}'
- name: Install node
  shell: |
    export NVM_DIR="{{NVM_DIR}}"
    source "$NVM_DIR/nvm.sh"
    nvm install {{NODE_VERSION}}
  args:
    executable: /bin/bash