---
# tasks file for iptables_deploy
- name: Allow tcp inbound traffic on 80 port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    jump: ACCEPT
- name: Allow tcp inbound traffic on 443 port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    jump: ACCEPT
- name: Allow inbound tcp traffic on 22 port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    jump: ACCEPT
- name: Allow inbound icmp traffic
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
- name: Deny all other traffic
  ansible.builtin.iptables:
    chain: INPUT
    protocol: all
    jump: DROP
- name: Allow all outbound traffic
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: all
    jump: ACCEPT