---
 - name: Install dependencies for project
   hosts: all
   roles: 
    - docker_install
    - node_install
    - dotnet_install
    - create_services
 - name: Configure firewall
   hosts: all
   roles:
    - iptables_deploy